// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { CustomVault$Type } from "./CustomVault";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["CustomVault"]: CustomVault$Type;
    ["contracts/CustomVault.sol:CustomVault"]: CustomVault$Type;
  }
}
