// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { FixedPointMathLib$Type } from "./FixedPointMathLib";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["FixedPointMathLib"]: FixedPointMathLib$Type;
    ["@rari-capital/solmate/src/utils/FixedPointMathLib.sol:FixedPointMathLib"]: FixedPointMathLib$Type;
  }
}
