// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface FixedPointMathLib$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "FixedPointMathLib",
  "sourceName": "@rari-capital/solmate/src/utils/FixedPointMathLib.sol",
  "abi": [],
  "bytecode": "0x60566050600b82828239805160001a6073146043577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220b1dcb75f1a32620a6f55b774126fc7c6e6dbdd26f09e96cd096dbd39215db19164736f6c63430008140033",
  "deployedBytecode": "0x73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220b1dcb75f1a32620a6f55b774126fc7c6e6dbdd26f09e96cd096dbd39215db19164736f6c63430008140033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "FixedPointMathLib",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<FixedPointMathLib$Type["abi"]>>;
  export function deployContract(
    contractName: "@rari-capital/solmate/src/utils/FixedPointMathLib.sol:FixedPointMathLib",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<FixedPointMathLib$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "FixedPointMathLib",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<FixedPointMathLib$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@rari-capital/solmate/src/utils/FixedPointMathLib.sol:FixedPointMathLib",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<FixedPointMathLib$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "FixedPointMathLib",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<FixedPointMathLib$Type["abi"]>>;
  export function getContractAt(
    contractName: "@rari-capital/solmate/src/utils/FixedPointMathLib.sol:FixedPointMathLib",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<FixedPointMathLib$Type["abi"]>>;
}
