// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { USDC$Type } from "./USDC";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["USDC"]: USDC$Type;
    ["contracts/USDC.sol:USDC"]: USDC$Type;
  }
}
