// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface SafeTransferLib$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "SafeTransferLib",
  "sourceName": "@rari-capital/solmate/src/utils/SafeTransferLib.sol",
  "abi": [],
  "bytecode": "0x60566050600b82828239805160001a6073146043577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea26469706673582212204f39960356e42d3caff99ee95f401b29aa4bf1746c3ca37cb6a08dba9893714264736f6c63430008140033",
  "deployedBytecode": "0x73000000000000000000000000000000000000000030146080604052600080fdfea26469706673582212204f39960356e42d3caff99ee95f401b29aa4bf1746c3ca37cb6a08dba9893714264736f6c63430008140033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "SafeTransferLib",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<SafeTransferLib$Type["abi"]>>;
  export function deployContract(
    contractName: "@rari-capital/solmate/src/utils/SafeTransferLib.sol:SafeTransferLib",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<SafeTransferLib$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "SafeTransferLib",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<SafeTransferLib$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@rari-capital/solmate/src/utils/SafeTransferLib.sol:SafeTransferLib",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<SafeTransferLib$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "SafeTransferLib",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<SafeTransferLib$Type["abi"]>>;
  export function getContractAt(
    contractName: "@rari-capital/solmate/src/utils/SafeTransferLib.sol:SafeTransferLib",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<SafeTransferLib$Type["abi"]>>;
}
