[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options


[rpc_endpoints]
goerli = "${GOERIL_RPC_URL}"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }